name: Docs-lint
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  docsite:
    name: Lint extra docsite docs and links
    permissions:
      contents: read
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Run collection docs linter
        run: antsibull-docs lint-collection-docs .
